import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import matter from 'gray-matter';
import { buildImagePrompt, extractSceneFromTitle, photoRealismWrapper } from './image-prompt.js';
import { atomicWriteFile, sleep } from './lib/retry.js';
import { geminiGenerateImage, isGeminiConfigured } from './gemini.js';

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const storiesDir = path.join(root, 'src', 'content', 'stories');
const imagesDir = path.join(root, 'public', 'images', 'stories');
const API_DELAY_MS = parseInt(process.env.API_DELAY_MS || '500', 10);

function slugFromPath(imagePath) {
  const base = path.basename(imagePath || '', path.extname(imagePath || ''));
  return base;
}

async function generateGeminiImage(title, category, slug, body) {
  if (!isGeminiConfigured()) {
    throw new Error('GEMINI_API_KEY not set');
  }
  fs.mkdirSync(imagesDir, { recursive: true });
  const dest = path.join(imagesDir, `${slug}.jpg`);
  const publicPath = `/images/stories/${slug}.jpg`;

  const tryGenerate = async (prompt) => {
    await geminiGenerateImage(prompt, dest);
    return true;
  };

  try {
    const prompt = await buildImagePrompt(title, category, body);
    if (await tryGenerate(prompt)) {
      return { path: publicPath, credit: 'Generated by AI (Gemini)' };
    }
  } catch (err) {
    console.warn(`  [Gemini Image] ${err.message}, retry…`);
    const fallbackPrompt = photoRealismWrapper(extractSceneFromTitle(`${title} ${body}`));
    await tryGenerate(fallbackPrompt);
    return { path: publicPath, credit: 'Generated by AI (Gemini)' };
  }
  return null;
}

async function main() {
  if (!isGeminiConfigured()) {
    console.error('Нужен GEMINI_API_KEY в .env');
    process.exit(1);
  }

  const files = fs.readdirSync(storiesDir).filter((f) => f.endsWith('.md'));
  let updated = 0;

  for (const file of files) {
    const filePath = path.join(storiesDir, file);
    const raw = fs.readFileSync(filePath, 'utf-8');
    const { data, content } = matter(raw);
    const slug = slugFromPath(data.image) || file.replace('.md', '');
    const jpgPath = path.join(imagesDir, `${slug}.jpg`);
    const needsImage = !fs.existsSync(jpgPath) || (data.image || '').endsWith('.svg');

    if (!needsImage) continue;

    const body = content.split('*Материал подготовлен')[0].trim();
    console.log(`🖼  ${data.title?.slice(0, 55)}…`);

    try {
      const result = await generateGeminiImage(data.title, data.category, slug, body);
      if (!result) {
        console.warn(`  ✗ не удалось сгенерировать`);
        continue;
      }

      data.image = result.path;
      data.image_credit = result.credit;
      atomicWriteFile(filePath, matter.stringify(content, data));

      const svgPath = path.join(imagesDir, `${slug}.svg`);
      if (fs.existsSync(svgPath)) fs.unlinkSync(svgPath);

      updated++;
      console.log(`  ✓ ${result.path}`);
      if (API_DELAY_MS > 0) await sleep(API_DELAY_MS);
    } catch (err) {
      console.warn(`  ✗ ${err.message}`);
    }
  }

  console.log(`\n✅ Картинок обновлено: ${updated}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
